DROP TABLE BOARD;
CREATE TABLE BOARD
(
	NO NUMBER PRIMARY KEY,
	WRITER VARCHAR2(100 BYTE),
	TITLE VARCHAR2(1000 BYTE),
	CONTENT VARCHAR2(4000 BYTE),
	CREATED DATE
);

DROP SEQUENCE BOARD_SEQ;
CREATE SEQUENCE BOARD_SEQ NOCACHE;