-- 테이블 삭제
DROP TABLE SCHEDULE;
DROP TABLE PLAYER;
DROP TABLE EVENT;
DROP TABLE NATION;

-- NATION 테이블 생성
CREATE TABLE NATION(
    N_CODE          NUMBER(3)         NOT NULL,
    N_NAME          VARCHAR2(30 BYTE) NOT NULL,
    N_PARTI_PERSON  NUMBER            DEFAULT 0,
    N_PARTI_EVENT   NUMBER,
    N_PREV_RANK     NUMBER,
    N_CURR_RANK     NUMBER
);

-- EVENT 테이블 생성
CREATE TABLE EVENT(
    E_CODE        NUMBER            NOT NULL,
    E_NAME        VARCHAR2(30 BYTE) NOT NULL,
    E_FIRST_YEAR  NUMBER(4),
    E_INFO        VARCHAR2(100 BYTE)
);

-- PLAYER 테이블 생성
CREATE TABLE PLAYER(
    P_CODE  NUMBER(3)         NOT NULL,
    P_NAME  VARCHAR2(30 BYTE) NOT NULL,
    N_CODE  NUMBER(3)         NOT NULL,
    E_CODE  NUMBER            NOT NULL,
    P_RANK  NUMBER,
    P_AGE   NUMBER(3)
);

-- SCHEDULE 테이블 생성
CREATE TABLE SCHEDULE(
    N_CODE        NUMBER(3) NOT NULL,
    E_CODE        NUMBER    NOT NULL,
    S_START_DATE  DATE,
    S_END_DATE    DATE,
    S_INFO        VARCHAR2(100 BYTE)
);

-- 1개 칼럼을 기본키로 설정
ALTER TABLE NATION ADD CONSTRAINT NATION_PK PRIMARY KEY(N_CODE);
ALTER TABLE EVENT  ADD CONSTRAINT EVENT_PK  PRIMARY KEY(E_CODE);
ALTER TABLE PLAYER ADD CONSTRAINT PLAYER_PK PRIMARY KEY(P_CODE);

-- 2개 칼럼을 기본키로 설정
ALTER TABLE SCHEDULE ADD CONSTRAINT SCHEDULE_PK PRIMARY KEY(N_CODE, E_CODE);

-- 외래키 설정
ALTER TABLE PLAYER
    ADD CONSTRAINT PLAYER_EVENT_FK FOREIGN KEY(E_CODE)
        REFERENCES EVENT(E_CODE);

ALTER TABLE PLAYER
    ADD CONSTRAINT PLAYER_NATION_FK FOREIGN KEY(N_CODE)
        REFERENCES NATION(N_CODE);

ALTER TABLE SCHEDULE
    ADD CONSTRAINT SCHEDULE_NATION_FK FOREIGN KEY(N_CODE)
        REFERENCES NATION(N_CODE);
        
ALTER TABLE SCHEDULE
    ADD CONSTRAINT SCHEDULE_EVENT_FK FOREIGN KEY(E_CODE)
        REFERENCES EVENT(E_CODE);