-- 테이블 삭제
DROP TABLE BOARDS;
DROP TABLE MEMBERS;

-- MEMBERS 테이블 (회원) 생성
CREATE TABLE MEMBERS(
    MEMBER_NO    NUMBER,
    MEMBER_ID    VARCHAR2(30 BYTE) NOT NULL UNIQUE,
    NAME         VARCHAR2(30 BYTE) NOT NULL,
    REGISTE_DATE TIMESTAMP
);

-- 기본키 설정
ALTER TABLE MEMBERS 
    ADD CONSTRAINT MEMBERS_PK PRIMARY KEY(MEMBER_NO);

-- BOARDS 테이블 (게시판) 생성
CREATE TABLE BOARDS(
    BOARD_NO    NUMBER,
    TITLE       VARCHAR2(1000 BYTE) NOT NULL,
    CONTENT     VARCHAR2(4000 BYTE),
    MEMBER_ID   VARCHAR2(30 BYTE)   NOT NULL,
    CREATE_DATE DATE
);

-- 기본키 설정
ALTER TABLE BOARDS 
    ADD CONSTRAINT BOARDS_PK PRIMARY KEY(BOARD_NO);

-- 외래키 설정
-- MEMBERS             BOARDS
-- MEMBER_ID(UNIQUE)   MEMBER_ID(FK)
ALTER TABLE BOARDS 
    ADD CONSTRAINT BOARDS_MEMBERS_FK FOREIGN KEY(MEMBER_ID) 
        REFERENCES MEMBERS(MEMBER_ID);

-- MEMBERS 테이블의 시퀀스
DROP SEQUENCE MEMBERS_SEQ;
CREATE SEQUENCE MEMBERS_SEQ
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    NOCACHE
    NOCYCLE;

-- BOARDS 테이블의 시퀀스
DROP SEQUENCE BOARDS_SEQ;
CREATE SEQUENCE BOARDS_SEQ
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    NOCACHE
    NOCYCLE;

-- 데이터 추가
INSERT INTO MEMBERS
    (MEMBER_NO, MEMBER_ID, NAME, REGISTE_DATE)
VALUES 
    (MEMBERS_SEQ.NEXTVAL, 'admin', '관리자', SYSTIMESTAMP);

INSERT INTO MEMBERS
    (MEMBER_NO, MEMBER_ID, NAME, REGISTE_DATE)
VALUES 
    (MEMBERS_SEQ.NEXTVAL, 'user', '사용자', SYSTIMESTAMP);

-- 데이터 추가
INSERT INTO BOARDS VALUES(BOARDS_SEQ.NEXTVAL, '제목1', '내용1', 'admin', SYSDATE);
INSERT INTO BOARDS VALUES(BOARDS_SEQ.NEXTVAL, '제목2', '내용2', 'user', SYSDATE);
INSERT INTO BOARDS VALUES(BOARDS_SEQ.NEXTVAL, '제목3', '내용3', 'admin', SYSDATE);
INSERT INTO BOARDS VALUES(BOARDS_SEQ.NEXTVAL, '제목4', '내용4', 'user', SYSDATE);
INSERT INTO BOARDS VALUES(BOARDS_SEQ.NEXTVAL, '제목5', '내용5', 'admin', SYSDATE);

COMMIT;




-- 인라인 뷰(INLINE VIEW)
-- 1. FROM절에서 사용하는 서브쿼리이다.
-- 2. 인라인 뷰는 대부분 테이블 형식을 반환하는 서브쿼리이다.
-- 3. 인라인 뷰에 별명(ALIAS)을 지정하고 사용한다.
-- 4. 인라인 뷰에서 조회한 칼럼만 메인쿼리가 사용할 수 있다.

-- 서브쿼리에서 BOARD_NO, TITLE, CONTENT, MEMBER_ID, CREATE_DATE 칼럼을 사용했으므로
-- 메인쿼리는 BOARD_NO, TITLE, CONTENT, MEMBER_ID, CREATE_DATE 칼럼만 사용할 수 있다.
SELECT BOARD_NO, TITLE, CONTENT, MEMBER_ID, CREATE_DATE
  FROM (SELECT BOARD_NO, TITLE, CONTENT, MEMBER_ID, CREATE_DATE
          FROM BOARDS);

-- 서브쿼리에 별명을 지정할 수 있다.
SELECT B.BOARD_NO, B.TITLE, B.CONTENT
  FROM (SELECT BOARD_NO, TITLE, CONTENT
          FROM BOARDS) B;




-- 가상 칼럼(PSEUDO COLUMN)
-- 1. 존재하지만 저장되어 있지 않은 칼럼이다.
-- 2. 사용할 수 있으나 일부 제약이 있다.
-- 3. 종류
--     1) ROWID  : 행ID, 해당 행의 물리적 저장 위치
--     2) ROWNUM : 행NUM, 해당 행의 번호



-- ROWID
SELECT
       ROWID
     , MEMBER_NO
     , MEMBER_ID
  FROM
       MEMBERS;

-- ROWID를 조건으로 사용하기
-- 오라클 최고의 조회 속도
SELECT MEMBER_NO, MEMBER_ID
  FROM MEMBERS
 WHERE ROWID = 'AAAGD9AABAAALHBAAA';  -- 실제로 사용할 수 없는 방식(대신 INDEX를 사용함)
 
 
 
-- ROWNUM
SELECT
       ROWNUM
     , BOARD_NO
     , TITLE
     , CONTENT
     , MEMBER_ID
     , CREATE_DATE
  FROM
       BOARDS
 WHERE
       MEMBER_ID = 'admin';
 
-- ROWNUM 칼럼의 사용 방법
-- 1. ROWNUM은 1을 포함하는 범위를 조건으로 사용할 수 있다.
-- 2. ROWNUM은 1을 포함하지 않는 범위를 조건으로 사용할 수 없다.
-- 3. ROWNUM에 별명(ALIAS)을 지정하고 별명을 이용해 1을 포함하지 않는 범위를 조건으로 사용할 수 있다.

SELECT BOARD_NO, TITLE
  FROM BOARDS
 WHERE ROWNUM = 1;   -- 가능

SELECT BOARD_NO, TITLE
  FROM BOARDS
 WHERE ROWNUM <= 3;  -- 가능

SELECT BOARD_NO, TITLE
  FROM BOARDS
 WHERE ROWNUM = 2;   -- 불가능


-- ROWNUM에 별명(ALIAS)을 추가하고 사용해서 ROWNUM = 2인 데이터를 조회하기

-- 1) 잘못된 방법
SELECT ROWNUM AS 글번호, BOARD_NO, TITLE, CONTENT, MEMBER_ID, CREATE_DATE
  FROM BOARDS
 WHERE 글번호 = 2;

-- 2) 인라인 뷰를 이용한 해결 방법
--    WHERE절 이전에 ROWNUM의 별명을 주면 해결
SELECT B.글번호, B.BOARD_NO, B.TITLE, B.CONTENT, B.MEMBER_ID, B.CREATE_DATE
  FROM (SELECT ROWNUM AS 글번호, BOARD_NO, TITLE, CONTENT, MEMBER_ID, CREATE_DATE
          FROM BOARDS) B
 WHERE B.글번호 = 2;



-- 1. BOARDS 테이블에서 3번째 게시글을 조회하시오.
SELECT B.RN, B.BOARD_NO, B.TITLE, B.CONTENT, B.MEMBER_ID, B.CREATE_DATE
  FROM (SELECT ROWNUM AS RN, BOARD_NO, TITLE, CONTENT, MEMBER_ID, CREATE_DATE
          FROM BOARDS) B
 WHERE B.RN = 3;


-- 2. BOARDS 테이블에서 2~4번째 게시글을 조회하시오.
SELECT B.RN, B.BOARD_NO, B.TITLE, B.CONTENT, B.MEMBER_ID, B.CREATE_DATE
  FROM (SELECT ROWNUM AS RN, BOARD_NO, TITLE, CONTENT, MEMBER_ID, CREATE_DATE
          FROM BOARDS) B
 WHERE B.RN BETWEEN 2 AND 4;


-- 3. 작성일자(CREATE_DATE) 기준으로 3번째 작성된 게시글을 조회하시오.
--    작성일자의 오름차순 정렬 이후 ROWNUM이 3인 데이터

-- 1) ROWNUM 칼럼
SELECT B.RN, B.BOARD_NO, B.TITLE, B.CONTENT, B.MEMBER_ID, B.CREATE_DATE
  FROM (SELECT ROWNUM AS RN, A.BOARD_NO, A.TITLE, A.CONTENT, A.MEMBER_ID, A.CREATE_DATE
          FROM (SELECT BOARD_NO, TITLE, CONTENT, MEMBER_ID, CREATE_DATE
                  FROM BOARDS
                 ORDER BY CREATE_DATE) A) B
 WHERE B.RN = 3;

-- 2) ROW_NUMBER() OVER(ORDER BY 칼럼)
SELECT B.RN, B.BOARD_NO, B.TITLE, B.CONTENT, B.MEMBER_ID, B.CREATE_DATE
  FROM (SELECT ROW_NUMBER() OVER(ORDER BY CREATE_DATE) AS RN, BOARD_NO, TITLE, CONTENT, MEMBER_ID, CREATE_DATE
          FROM BOARDS) B
 WHERE B.RN = 3;

-- 3) RANK() OVER(ORDER BY 칼럼) : 동일한 순위(행번호)는 같은 번호 부여
SELECT B.RN, B.BOARD_NO, B.TITLE, B.CONTENT, B.MEMBER_ID, B.CREATE_DATE
  FROM (SELECT RANK() OVER(ORDER BY CREATE_DATE) AS RN, BOARD_NO, TITLE, CONTENT, MEMBER_ID, CREATE_DATE
          FROM BOARDS) B
 WHERE B.RN = 3;



-- 4. 작성일자(CREATE_DATE) 기준으로 2~4번째로 작성한 게시글을 조회하시오.

-- 1) ROWNUM 칼럼
SELECT B.RN, B.BOARD_NO, B.TITLE, B.CONTENT, B.MEMBER_ID, B.CREATE_DATE
  FROM (SELECT ROWNUM AS RN, A.BOARD_NO, A.TITLE, A.CONTENT, A.MEMBER_ID, A.CREATE_DATE
          FROM (SELECT BOARD_NO, TITLE, CONTENT, MEMBER_ID, CREATE_DATE
                  FROM BOARDS
                 ORDER BY CREATE_DATE) A) B
 WHERE B.RN BETWEEN 2 AND 4;

-- 2) ROW_NUMBER() OVER(ORDER BY 칼럼)
SELECT B.RN, B.BOARD_NO, B.TITLE, B.CONTENT, B.MEMBER_ID, B.CREATE_DATE
  FROM (SELECT ROW_NUMBER() OVER(ORDER BY CREATE_DATE) AS RN, BOARD_NO, TITLE, CONTENT, MEMBER_ID, CREATE_DATE
          FROM BOARDS) B
 WHERE B.RN BETWEEN 2 AND 4;

-- 3) RANK() OVER(ORDER BY 칼럼)
SELECT B.RN, B.BOARD_NO, B.TITLE, B.CONTENT, B.MEMBER_ID, B.CREATE_DATE
  FROM (SELECT RANK() OVER(ORDER BY CREATE_DATE) AS RN, BOARD_NO, TITLE, CONTENT, MEMBER_ID, CREATE_DATE
          FROM BOARDS) B
 WHERE B.RN BETWEEN 2 AND 4;
