-- 테이블 삭제
DROP TABLE BOARDS;

-- 테이블 생성
CREATE TABLE BOARDS(
	NO NUMBER,
	TITLE VARCHAR2(1000 BYTE) NOT NULL,
	HIT NUMBER,
	CREATED DATE
);

-- 기본키
ALTER TABLE BOARDS
	ADD CONSTRAINT BOARDS_PK PRIMARY KEY(NO);

-- 시퀀스
DROP SEQUENCE BOARDS_SEQ;
CREATE SEQUENCE BOARDS_SEQ NOCACHE;