DROP TABLE PRODUCT;
CREATE TABLE PRODUCT(
	NO NUMBER,
	NAME VARCHAR2(20 BYTE),
	PRICE NUMBER
);
ALTER TABLE PRODUCT
	ADD CONSTRAINT PRODUCT_PK PRIMARY KEY(NO);

DROP SEQUENCE PRODUCT_SEQ;
CREATE SEQUENCE PRODUCT_SEQ NOCACHE;
