-- 댓글
DROP TABLE REPLY;
CREATE TABLE REPLY
(
    REPLY_NO NUMBER NOT NULL,
    WRITER VARCHAR2(100 BYTE) NOT NULL,
    CONTENT VARCHAR2(400 BYTE) NOT NULL,
    IP VARCHAR2(32 BYTE),
    BOARD_NO NUMBER,
    CREATED DATE
);

-- 게시판
DROP TABLE BOARD;
CREATE TABLE BOARD
(
    BOARD_NO NUMBER NOT NULL,
    WRITER VARCHAR2(100 BYTE) NOT NULL,
    TITLE VARCHAR2(100 BYTE) NOT NULL,
    CONTENT VARCHAR2(400 BYTE),
    HIT NUMBER,
    IP VARCHAR2(32 BYTE),
    CREATED DATE,
    MODIFIED DATE
);

-- 게시판 기본키
ALTER TABLE BOARD
    ADD CONSTRAINT BOARD_PK
        PRIMARY KEY(BOARD_NO);

-- 댓글 기본키
ALTER TABLE REPLY
    ADD CONSTRAINT REPLY_PK
        PRIMARY KEY(REPLY_NO);

-- 댓글 외래키1 : 댓글이 존재하는 게시글은 삭제할 수 없다.
ALTER TABLE REPLY
    ADD CONSTRAINT REPLY_BOARD_FK
        FOREIGN KEY(BOARD_NO)
            REFERENCES BOARD(BOARD_NO);

-- 댓글 외래키2 : 댓글이 존재하는 게시글을 삭제하면 댓글이 함께 삭제된다.
--ALTER TABLE REPLY
--    ADD CONSTRAINT REPLY_BOARD_FK
--        FOREIGN KEY(BOARD_NO)
--            REFERENCES BOARD(BOARD_NO) ON DELETE CASCADE;

-- 시퀀스
DROP SEQUENCE BOARD_SEQ;
DROP SEQUENCE REPLY_SEQ;
CREATE SEQUENCE BOARD_SEQ NOCACHE;
CREATE SEQUENCE REPLY_SEQ NOCACHE;