DROP TABLE BOOK;
DROP SEQUENCE BOOK_SEQ;

CREATE TABLE BOOK(
    NO NUMBER,
    TITLE VARCHAR2(300 BYTE),
    LINK VARCHAR2(300 BYTE),
    IMAGE VARCHAR2(300 BYTE),
    AUTHOR VARCHAR2(50 BYTE),
    PRICE NUMBER,
    DISCOUNT NUMBER,
    PUBLISHER VARCHAR2(50 BYTE),
    ISBN VARCHAR2(25 BYTE),
    DESCRIPTION VARCHAR2(1000 BYTE),
    PUBDATE DATE
);
ALTER TABLE BOOK
    ADD CONSTRAINT BOOK_PK PRIMARY KEY(NO);

CREATE SEQUENCE BOOK_SEQ NOCACHE;