-- 관리자 계정 : root
-- 관리자 비번 : 1111
-- 스키마 : spring
-- WorkBench를 실행하고 '스키마'부터 만들어야 합니다. Oracle의 '사용자' 같은 개념입니다.


USE SPRING;  -- 지금부터 spring 스키마에서 작업한다.

DROP TABLE IF EXISTS NOTICE;
DROP TABLE IF EXISTS MEMBER;
CREATE TABLE MEMBER
(
    MEMBER_NO BIGINT NOT NULL AUTO_INCREMENT,
    MEMBER_NAME VARCHAR(50),
    CONSTRAINT MEMBER_PK PRIMARY KEY(MEMBER_NO)
);
CREATE TABLE NOTICE
(
    NOTICE_NO BIGINT NOT NULL AUTO_INCREMENT,
    MEMBER_NO BIGINT,
    TITLE VARCHAR(1000),
    CONTENT VARCHAR(1000),
    CREATED_DATE DATETIME,
    MODIFIED_DATE DATETIME,
    CONSTRAINT NOTICE_PK PRIMARY KEY(NOTICE_NO)
);
ALTER TABLE NOTICE
	ADD CONSTRAINT NOTICE_MEMBER_FK
		FOREIGN KEY(MEMBER_NO) REFERENCES MEMBER(MEMBER_NO)
			ON DELETE SET NULL;  -- 사용자가 삭제되면 공지사항의 작성자는 NULL 값이 채워진다.

INSERT INTO MEMBER(MEMBER_NAME) VALUES ('제임스');
INSERT INTO MEMBER(MEMBER_NAME) VALUES ('에밀리');
INSERT INTO MEMBER(MEMBER_NAME) VALUES ('크리스틴');
COMMIT;

INSERT INTO NOTICE(MEMBER_NO, TITLE, CONTENT, CREATED_DATE, MODIFIED_DATE) VALUES (1, '공지1', '내용1', NOW(), NOW());
INSERT INTO NOTICE(MEMBER_NO, TITLE, CONTENT, CREATED_DATE, MODIFIED_DATE) VALUES (1, '공지2', '내용2', NOW(), NOW());
INSERT INTO NOTICE(MEMBER_NO, TITLE, CONTENT, CREATED_DATE, MODIFIED_DATE) VALUES (1, '공지3', '내용3', NOW(), NOW());
INSERT INTO NOTICE(MEMBER_NO, TITLE, CONTENT, CREATED_DATE, MODIFIED_DATE) VALUES (1, '공지4', '내용4', NOW(), NOW());
INSERT INTO NOTICE(MEMBER_NO, TITLE, CONTENT, CREATED_DATE, MODIFIED_DATE) VALUES (1, '공지5', '내용5', NOW(), NOW());
INSERT INTO NOTICE(MEMBER_NO, TITLE, CONTENT, CREATED_DATE, MODIFIED_DATE) VALUES (1, '공지6', '내용6', NOW(), NOW());
INSERT INTO NOTICE(MEMBER_NO, TITLE, CONTENT, CREATED_DATE, MODIFIED_DATE) VALUES (1, '공지7', '내용7', NOW(), NOW());
INSERT INTO NOTICE(MEMBER_NO, TITLE, CONTENT, CREATED_DATE, MODIFIED_DATE) VALUES (3, '공지8', '내용8', NOW(), NOW());
INSERT INTO NOTICE(MEMBER_NO, TITLE, CONTENT, CREATED_DATE, MODIFIED_DATE) VALUES (3, '공지9', '내용9', NOW(), NOW());
INSERT INTO NOTICE(MEMBER_NO, TITLE, CONTENT, CREATED_DATE, MODIFIED_DATE) VALUES (3, '공지10', '내용10', NOW(), NOW());
INSERT INTO NOTICE(MEMBER_NO, TITLE, CONTENT, CREATED_DATE, MODIFIED_DATE) VALUES (3, '공지11', '내용11', NOW(), NOW());
INSERT INTO NOTICE(MEMBER_NO, TITLE, CONTENT, CREATED_DATE, MODIFIED_DATE) VALUES (3, '공지12', '내용12', NOW(), NOW());
INSERT INTO NOTICE(MEMBER_NO, TITLE, CONTENT, CREATED_DATE, MODIFIED_DATE) VALUES (3, '공지13', '내용13', NOW(), NOW());
INSERT INTO NOTICE(MEMBER_NO, TITLE, CONTENT, CREATED_DATE, MODIFIED_DATE) VALUES (2, '공지14', '내용14', NOW(), NOW());
INSERT INTO NOTICE(MEMBER_NO, TITLE, CONTENT, CREATED_DATE, MODIFIED_DATE) VALUES (2, '공지15', '내용15', NOW(), NOW());
INSERT INTO NOTICE(MEMBER_NO, TITLE, CONTENT, CREATED_DATE, MODIFIED_DATE) VALUES (2, '공지16', '내용16', NOW(), NOW());
INSERT INTO NOTICE(MEMBER_NO, TITLE, CONTENT, CREATED_DATE, MODIFIED_DATE) VALUES (2, '공지17', '내용17', NOW(), NOW());
INSERT INTO NOTICE(MEMBER_NO, TITLE, CONTENT, CREATED_DATE, MODIFIED_DATE) VALUES (2, '공지18', '내용18', NOW(), NOW());
INSERT INTO NOTICE(MEMBER_NO, TITLE, CONTENT, CREATED_DATE, MODIFIED_DATE) VALUES (2, '공지19', '내용19', NOW(), NOW());
INSERT INTO NOTICE(MEMBER_NO, TITLE, CONTENT, CREATED_DATE, MODIFIED_DATE) VALUES (2, '공지20', '내용20', NOW(), NOW());
COMMIT;
