DROP TABLE PRODUCT;
CREATE TABLE PRODUCT
(
	PRODUCT_NO NUMBER PRIMARY KEY,
	NAME VARCHAR2(20 BYTE) NOT NULL UNIQUE,
	PRICE NUMBER,
	IMAGE VARCHAR2(300 BYTE)
);

DROP SEQUENCE PRODUCT_SEQ;
CREATE SEQUENCE PRODUCT_SEQ NOCACHE;
