DROP TABLE BOARD1;
CREATE TABLE BOARD1
(
	NO NUMBER PRIMARY KEY,
	WRITER VARCHAR2(100 BYTE),
	TITLE VARCHAR2(1000 BYTE) NOT NULL,
	HIT NUMBER,
	CREATED DATE,
);

DROP SEQUENCE BOARD_SEQ;
CREATE SEQUENCE BOARD_SEQ;